version: '3'

services:
    backend: 
      image: frederikkelan/backend:1.0.0
      ports:
        - "9000:9000"
      depends_on:
        - redis
      environment:
        - REDIS_DNS=redis

    frontend:
      image: frederikkelan/frontend:1.0.0
      ports: 
      - "8080:8080"
      depends_on:
      - backend
      environment:
      - BACKEND_DNS=backend

    redis:
      image: redis
      ports:
      - "6379:6379"


