version: 'latest'

services:
    backend: 
      image: simple-fortune-cookie-backend
      ports:
      - "8000:8000"
      depends_on:
      - redis


    frontend:
      image: simple-fortune-cookie-frontend
      ports: 
      - "8080:8080"
      depends_on:
      - backend

    redis:
      image: redis
      ports: 
      - "6379:6379"


