version: '3'

services:
    backend: 
      image: simple-fortune-cookie-backend
      ports:
        - "9000:9000"
      depends_on:
        - redis
      environment:
        - REDIS_DNS=redis


    frontend:
      image: simple-fortune-cookie-frontend
      ports: 
      - "8080:8080"
      depends_on:
      - backend
      environment:
      - BACKEND_DNS=backend

    redis:
      image: redis
      ports: 
      - "6379:6379"
      volumes:
      - redis:/data:rw

volumes:
  redis:


