apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backend
  labels:
    app: backend 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata: 
      creationTimestamp: null
      labels: 
        app: backend
    spec:
      containers:
        - image: qnudsgaard/simple-fortune-cookie-backend:latest
          name: backend
          resources: {}
status: {}