apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  ports:
    - name: "6379"
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: db
  type: ClusterIP
status:
  loadBalancer: {}