apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend      # arbitrary label on deployment
spec:
  replicas: 1
  selector:
    matchLabels:        # labels the replica selector should match
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend    # label for replica selector to match
        # arbitrary label we can match on elsewhere
    spec:
      containers:
      - image:  frederikkelan/frontend:1.0.0
        name: frontend 
        resources: {}
status: {}