name: CI
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, test, dev ] #Augment your script such that you can deploy multiple versions ( eg. development, staging, production ), depending on the PR branch name

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Run go test
        run: cd frontend && go test
  Build-and-push:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}