name: CI
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
on:
  #Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Clone-down:
    name: Clown-down-repo
    runs-on: ubuntu-latest
    container: golang:1.8.5 
    steps:
      - name: Clone down repo
        uses: actions/checkout@v2
      - name: Upload repo
        uses: actions/upload-artifact@v2 
        with:
          name: clone-down
          path: .